/* SEQUENCES */
CREATE SEQUENCE BeerSEQ START WITH 1;
CREATE SEQUENCE KegSEQ START WITH 1;

/* DATA GENERATION PROCEDURE */
BEGIN
  FOR i IN 1..37500 LOOP    
    IF MOD(KegSEQ.nextval, 5) = 1 THEN
        INSERT INTO BeerInKegs(beerID, kegID) VALUES (BeerSEQ.nextval, KegSEQ.currval);
    ElSE
        INSERT INTO BeerInKegs(beerID, kegID) VALUES (BeerSEQ.currval, KegSEQ.currval); 
    END IF;
  END LOOP;
END;
/

/* DROP DATA NECESSARY ONLY FOR DATABASE FILL */
DROP SEQUENCE KegSEQ;
DROP SEQUENCE BeerSEQ;